## Numpy

Импортировать NumPy под именем np

In [1]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [4]:
vector_null = np.zeros(10)

Создать вектор размера 10, заполненный единицами

In [5]:
vector_ones = np.ones(10)

Создать вектор размера 10, заполненный числом 2.5

In [11]:
vector_25 = np.ones(10)*2.5

Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [13]:
vector_ = np.zeros(10)
vector_[4] = 1

Развернуть вектор (первый становится последним)

In [27]:
vector_reverce = np.arange(10) 
vector_reverce = vector_reverce[::-1]

Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [29]:
matrix = np.arange(9).reshape(3,3)

Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [33]:
not_null = np.nonzero([1,2,0,0,4,0])

Создать 3x3 единичную матрицу

In [32]:
matrix1 = np.eye(3)

Создать массив 3x3x3 со случайными значениями

In [37]:
rnd = np.random.random((3,3,3))

Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [42]:
rnd_1 = np.random.random((30))
meanV = rnd_1.mean()

Перемножить матрицы 5x3 и 3x2

In [45]:
Matr53 = np.arange(15).reshape(5,3)
Matr32 = np.arange(6).reshape(3,2)
Matr5332 = np.dot(Matr53,Matr32)

Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [50]:
RndV = np.linspace(0,1,12)[1:-1]
print(RndV)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


Заменить максимальный элемент на ноль

In [54]:
array_ = np.arange(10,20)
array_[array_.argmax()] = 0

Преобразовать массив из float в int

In [70]:
Mas1 = np.arange(10, dtype=np.float32)
MasInt = Mas1.astype(np.int32, copy=False)

Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [89]:
import scipy.spatial as scispa
Mass = np.random.random((10,2))
print(Mass)
MassDistance = scispa.distance.cdist(Mass,Mass)
print(MassDistance)

[[0.96166981 0.46595675]
 [0.27147107 0.59272851]
 [0.397331   0.29984147]
 [0.25393171 0.06451672]
 [0.52761357 0.84953028]
 [0.77291404 0.71883875]
 [0.87563358 0.71530563]
 [0.76467455 0.03732326]
 [0.61488601 0.48420656]
 [0.40293385 0.67273034]]
[[0.         0.70174452 0.58827934 0.8136629  0.57925251 0.31555989
  0.26377471 0.47173488 0.34726367 0.59576941]
 [0.70174452 0.         0.31878447 0.52850291 0.36270667 0.51705788
  0.6164718  0.7427817  0.3601539  0.15389202]
 [0.58827934 0.31878447 0.         0.27557412 0.5649171  0.56269116
  0.63354859 0.45150537 0.28516779 0.37293095]
 [0.8136629  0.52850291 0.27557412 0.         0.83135315 0.83515267
  0.9000219  0.51146625 0.553559   0.62619921]
 [0.57925251 0.36270667 0.5649171  0.83135315 0.         0.27794352
  0.37300695 0.84609583 0.37560338 0.21634059]
 [0.31555989 0.51705788 0.56269116 0.83515267 0.27794352 0.
  0.10278028 0.6815653  0.28288712 0.37284223]
 [0.26377471 0.6164718  0.63354859 0.9000219  0.37300695 0.10278028

Случайно расположить p элементов в 2D массив

In [96]:
# ввод размерности массива
n = int(input("размерность -")) 
# ввод количества элементов
p = int(input("количество размещаемых элементов -"))
Mas = np.zeros((n,n))
print(Mas)
elm = int(input("какой элемент разместить -"))
np.put(Mas, np.random.choice(range(n*n), p, replace=False), elm)
print(Mas)

размерность -5
количество размещаемых элементов -3
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
какой элемент разместить -6
[[0. 0. 0. 0. 6.]
 [0. 0. 6. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 6. 0.]]


Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [102]:
Mass_ = np.array([1,2,3,4,5])
Mass0 = np.zeros(len(Mass_) + (len(Mass_)-1)*3)
Mass0[::4] = Mass_
print(Mass0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


Найти наиболее частое значение в массиве

In [121]:
Mass = np.random.randint(1,5,10)
print(Mass)
print(np.bincount(Mass))
print(np.bincount(Mass).argmax())

[4 3 4 3 1 3 3 1 2 1]
[0 3 1 4 2]
3


Найти n наибольших значений в массиве

In [132]:
MMM = np.random.random(15)
print(MMM)
# ввод количества значений
n = int(input("кол-во наибольших значений - ")) 
print (MMM[np.argpartition(-MMM,n)[:n]])


[0.86231391 0.14123744 0.61871526 0.35791753 0.65773945 0.45675093
 0.20663507 0.73601846 0.49239905 0.27471816 0.37663394 0.33188849
 0.2760608  0.48880349 0.98533647]
кол-во наибольших значений - 3
[0.98533647 0.86231391 0.73601846]


## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

In [133]:
import pandas as pd
df = pd.read_csv('en.openfoodfacts.org.products.tsv', sep='\t')

/Users/Natalia/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (0,3,5,19,20,24,25,26,27,28,36,37,38,39,48) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


Посмотреть первые 5 записей

In [135]:
df.head()

code                                                url  \
0   3087  http://world-en.openfoodfacts.org/product/0000...   
1   4530  http://world-en.openfoodfacts.org/product/0000...   
2   4559  http://world-en.openfoodfacts.org/product/0000...   
3  16087  http://world-en.openfoodfacts.org/product/0000...   
4  16094  http://world-en.openfoodfacts.org/product/0000...   

                      creator   created_t      created_datetime  \
0  openfoodfacts-contributors  1474103866  2016-09-17T09:17:46Z   
1             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
2             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
3             usda-ndb-import  1489055731  2017-03-09T10:35:31Z   
4             usda-ndb-import  1489055653  2017-03-09T10:34:13Z   

  last_modified_t last_modified_datetime                    product_name  \
0      1474103893   2016-09-17T09:18:13Z              Farine de blé noir   
1      1489069957   2017-03-09T14:32:37Z  Banana Chips Sweetened (Whole)   
2      1489069957   2017-03-09T14:32:37Z                         Peanuts   
3      1489055731   2017-03-09T10:35:31Z          Organic Salted Nut Mix   
4      1489055653   2017-03-09T10:34:13Z                 Organic Polenta   

  generic_name quantity         ...         fruits-vegetables-nuts_100g  \
0          NaN      1kg         ...                                 NaN   
1          NaN      NaN         ...                                 NaN   
2          NaN      NaN         ...                                 NaN   
3          NaN      NaN         ...                                 NaN   
4          NaN      NaN         ...                                 NaN   

  fruits-vegetables-nuts-estimate_100g collagen-meat-protein-ratio_100g  \
0                                  NaN                              NaN   
1                                  NaN                              NaN   
2                                  NaN                              NaN   
3                                  NaN                              NaN   
4                                  NaN                              NaN   

  cocoa_100g chlorophyl_100g carbon-footprint_100g nutrition-score-fr_100g  \
0        NaN             NaN                   NaN                     NaN   
1        NaN             NaN                   NaN                    14.0   
2        NaN             NaN                   NaN                     0.0   
3        NaN             NaN                   NaN                    12.0   
4        NaN             NaN                   NaN                     NaN   

  nutrition-score-uk_100g glycemic-index_100g water-hardness_100g  
0                     NaN                 NaN                 NaN  
1                    14.0                 NaN                 NaN  
2                     0.0                 NaN                 NaN  
3                    12.0                 NaN                 NaN  
4                     NaN                 NaN                 NaN  

[5 rows x 163 columns]

Сколько наблюдений в наборе данных?


In [136]:
df.info()
#356027 записей

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 356027 entries, 0 to 356026
Columns: 163 entries, code to water-hardness_100g
dtypes: float64(107), object(56)
memory usage: 442.8+ MB


Сколько столбцов в наборе данных?

In [137]:
df.info()
#163 столбца

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 356027 entries, 0 to 356026
Columns: 163 entries, code to water-hardness_100g
dtypes: float64(107), object(56)
memory usage: 442.8+ MB


Напечатайте все названия столбцов

In [142]:
print(df.columns.values)

['code' 'url' 'creator' 'created_t' 'created_datetime' 'last_modified_t'
 'last_modified_datetime' 'product_name' 'generic_name' 'quantity'
 'packaging' 'packaging_tags' 'brands' 'brands_tags' 'categories'
 'categories_tags' 'categories_en' 'origins' 'origins_tags'
 'manufacturing_places' 'manufacturing_places_tags' 'labels' 'labels_tags'
 'labels_en' 'emb_codes' 'emb_codes_tags' 'first_packaging_code_geo'
 'cities' 'cities_tags' 'purchase_places' 'stores' 'countries'
 'countries_tags' 'countries_en' 'ingredients_text' 'allergens'
 'allergens_en' 'traces' 'traces_tags' 'traces_en' 'serving_size'
 'no_nutriments' 'additives_n' 'additives' 'additives_tags' 'additives_en'
 'ingredients_from_palm_oil_n' 'ingredients_from_palm_oil'
 'ingredients_from_palm_oil_tags'
 'ingredients_that_may_be_from_palm_oil_n'
 'ingredients_that_may_be_from_palm_oil'
 'ingredients_that_may_be_from_palm_oil_tags' 'nutrition_grade_uk'
 'nutrition_grade_fr' 'pnns_groups_1' 'pnns_groups_2' 'states'
 'states_tags' 

Какое название у 105 столбца?

In [146]:
print(df.columns.values[104])
# -glucose_100g

-glucose_100g


Какой тип наблюдений в 105 столбце?

In [162]:
df['-glucose_100g'].dtype
#float64

dtype('float64')

Как проиндексирован набор данных?

In [164]:
df.index
# RangeIndex(start=0, stop=356027, step=1)

RangeIndex(start=0, stop=356027, step=1)

Каково значение имени продукта в 19-м наблюдении?

In [168]:
df['product_name'][20]
# "Energy Power Mix"

'Energy Power Mix'

## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

In [251]:
import pandas as pd
chipo = pd.read_csv('chipotle.tsv', sep='\t')

Как много продуктов стоят более чем $10.00?

In [3]:
import pandas as pd
chipo = pd.read_csv('chipotle.tsv', sep='\t')
# убираем знак $ в столбце с ценой
chipo['item_price'] = chipo['item_price'].map(lambda x: str(x)[1:])
# преобразование цены в числовой формат
chipo['item_price']=pd.to_numeric(chipo['item_price'])
# вычисление количества продуктов с ценой более $10

chipo[chipo["item_price"]/chipo["quantity"]>10]["item_price"].count()
#1130 записей с ценой больше $10

1034

Какова цена каждого предмета? Напечатать столбцы item_name и item_price

In [4]:
chipoExp = chipo[chipo["item_price"]/chipo["quantity"]>10]
chipoExp[["item_name","item_price"]]

item_name  item_price
5           Chicken Bowl       10.98
7          Steak Burrito       11.75
13          Chicken Bowl       11.25
23       Chicken Burrito       10.98
39         Barbacoa Bowl       11.75
42          Chicken Bowl       11.25
43         Steak Burrito       11.75
45       Chicken Burrito       10.98
52       Chicken Burrito       10.98
57        Veggie Burrito       11.25
58         Barbacoa Bowl       11.75
62           Veggie Bowl       11.25
68       Chicken Burrito       10.98
79    Chicken Soft Tacos       11.25
90            Steak Bowl       11.75
91            Steak Bowl       11.75
93      Carnitas Burrito       11.75
97         Carnitas Bowl       11.75
123         Chicken Bowl       11.25
130     Barbacoa Burrito       11.75
134      Chicken Burrito       10.98
135   Chicken Salad Bowl       22.50
136        Barbacoa Bowl       11.75
138         Chicken Bowl       11.25
140         Chicken Bowl       11.25
142         Chicken Bowl       11.25
143          Veggie Bowl       11.25
144     Barbacoa Burrito       11.75
147        Steak Burrito       11.48
157          Veggie Bowl       11.25
...                  ...         ...
4502  Chicken Soft Tacos       11.25
4504       Carnitas Bowl       11.75
4506        Chicken Bowl       11.25
4510       Barbacoa Bowl       11.49
4518          Steak Bowl       11.75
4521     Chicken Burrito       11.25
4523  Steak Crispy Tacos       11.75
4533     Chicken Burrito       11.25
4540        Chicken Bowl       11.25
4553        Chicken Bowl       11.25
4554  Steak Crispy Tacos       11.75
4556     Chicken Burrito       11.25
4559     Chicken Burrito       11.25
4564        Chicken Bowl       11.25
4576        Chicken Bowl       11.25
4580  Chicken Salad Bowl       11.25
4586        Chicken Bowl       11.25
4587        Chicken Bowl       11.25
4589        Chicken Bowl       11.25
4590        Chicken Bowl       11.25
4592    Barbacoa Burrito       11.75
4593       Carnitas Bowl       11.75
4594       Barbacoa Bowl       11.75
4607       Steak Burrito       11.75
4608      Veggie Burrito       11.25
4610       Steak Burrito       11.75
4611      Veggie Burrito       11.25
4617       Steak Burrito       11.75
4618       Steak Burrito       11.75
4619  Chicken Salad Bowl       11.25

[1034 rows x 2 columns]

Отсортировать по имени предмета

In [5]:
chipoExp = chipo[chipo["item_price"]/chipo["quantity"]>10]
#сортировка по столбцу item_name
chipoExp.sort_values(['item_name'], ascending=True)

order_id  quantity          item_name  \
1175       483         1      Barbacoa Bowl   
2013       812         1      Barbacoa Bowl   
2073       836         1      Barbacoa Bowl   
4485      1786         1      Barbacoa Bowl   
471        202         1      Barbacoa Bowl   
4140      1657         1      Barbacoa Bowl   
1746       705         1      Barbacoa Bowl   
4046      1619         1      Barbacoa Bowl   
4510      1793         1      Barbacoa Bowl   
2749      1091         1      Barbacoa Bowl   
2762      1097         1      Barbacoa Bowl   
1643       664         1      Barbacoa Bowl   
4380      1748         1      Barbacoa Bowl   
136         61         1      Barbacoa Bowl   
919        380         1      Barbacoa Bowl   
3017      1200         1      Barbacoa Bowl   
4441      1770         1      Barbacoa Bowl   
1236       504         1      Barbacoa Bowl   
3025      1203         1      Barbacoa Bowl   
3394      1361         1      Barbacoa Bowl   
1174       483         1      Barbacoa Bowl   
58          27         1      Barbacoa Bowl   
1235       504         1      Barbacoa Bowl   
39          19         1      Barbacoa Bowl   
4594      1825         1      Barbacoa Bowl   
1383       562         1      Barbacoa Bowl   
3547      1426         1      Barbacoa Bowl   
4347      1736         1   Barbacoa Burrito   
450        195         1   Barbacoa Burrito   
375        163         1   Barbacoa Burrito   
...        ...       ...                ...   
2911      1157         1     Veggie Burrito   
3113      1243         1     Veggie Burrito   
3542      1424         1     Veggie Burrito   
3601      1443         3     Veggie Burrito   
4319      1723         1     Veggie Burrito   
479        205         1     Veggie Burrito   
225         99         1     Veggie Burrito   
973        400         1     Veggie Burrito   
931        384         1     Veggie Burrito   
3235      1294         1     Veggie Burrito   
1631       658         1     Veggie Burrito   
394        171         1     Veggie Burrito   
4471      1782         1     Veggie Burrito   
4278      1706         1     Veggie Burrito   
874        361         1     Veggie Burrito   
1695       687         1     Veggie Burrito   
1105       456         1     Veggie Burrito   
3404      1366         1     Veggie Burrito   
496        207         1  Veggie Salad Bowl   
4109      1646         1  Veggie Salad Bowl   
3223      1289         1  Veggie Salad Bowl   
2156       869         1  Veggie Salad Bowl   
186         83         1  Veggie Salad Bowl   
455        195         1  Veggie Salad Bowl   
4201      1677         1  Veggie Salad Bowl   
1884       760         1  Veggie Salad Bowl   
4261      1700         1  Veggie Salad Bowl   
295        128         1  Veggie Salad Bowl   
738        304         1  Veggie Soft Tacos   
1699       688         1  Veggie Soft Tacos   

                                     choice_description  item_price  
1175  [Fresh Tomato Salsa (Mild), [Black Beans, Rice...       11.48  
2013  [Tomatillo Red Chili Salsa, [Black Beans, Chee...       11.75  
2073  [Tomatillo Green Chili Salsa, [Fajita Vegetabl...       11.75  
4485  [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...       11.75  
471   [[Tomatillo-Green Chili Salsa (Medium), Roaste...       11.48  
4140  [Tomatillo Red Chili Salsa, [Fajita Vegetables...       11.75  
1746  [Tomatillo Red Chili Salsa, [Cheese, Sour Crea...       11.75  
4046  [Tomatillo Green Chili Salsa, [Fajita Vegetabl...       11.75  
4510                                        [Guacamole]       11.49  
2749  [Fresh Tomato Salsa, [Rice, Black Beans, Chees...       11.75  
2762  [Tomatillo Red Chili Salsa, [Rice, Fajita Vege...       11.75  
1643  [Fresh Tomato Salsa, [Rice, Black Beans, Chees...       11.75  
4380  [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...       11.75  
136   [Tomatillo Red Chili Salsa, [Fajita Vegetables...       11.75  
919   [Tomatillo Red Chili Salsa, [Fajita

Сколько было заказано самого дорогого предмета?

In [10]:
import pandas as pd
chipo = pd.read_csv('chipotle.tsv', sep='\t')
# убираем знак $ в столбце с ценой
chipo['item_price'] = chipo['item_price'].map(lambda x: str(x)[1:])
# преобразование цены в числовой формат
chipo['item_price']=pd.to_numeric(chipo['item_price'])
#самый дорогой предмет
chipoMax = chipo['item_price']/chipo['quantity']
print(chipoMax.max())
#сколько раз купили самый дорогой предмет
CountExp = chipo[chipo['item_price']/chipo['quantity']==chipoMax]["item_name"].count()
print(CountExp)

11.89
4622


Сколько раз был заказан предмет "Veggie Salad Bowl"?

In [303]:
#вычисляем сколько раз делали заказ на Veggie Salad Bowl
VeggieCount = chipo[chipo["item_name"]=="Veggie Salad Bowl"]['item_name'].count()
print(VeggieCount)

18


Сколько раз люди заказали более чем 1 предмет "Canned Soda"?

In [302]:
import pandas as pd
chipo = pd.read_csv('chipotle.tsv', sep='\t')
# убираем знак $ в столбце с ценой
chipo['item_price'] = chipo['item_price'].map(lambda x: str(x)[1:])
# преобразование цены в числовой формат
chipo['item_price']=pd.to_numeric(chipo['item_price'])
# данные с Canned Soda
chipoSoda = chipo[chipo["item_name"]=="Canned Soda"]
# сколько раз заказывали более чем один предмет Canned Soda
chipoSodaResult = chipoSoda[chipoSoda["quantity"]>1]["item_name"].count()
print(chipoSodaResult)

20
